### ISSUE TITLE
DOC: add a doc link in the README

### ISSUE THREAD

**Issue by mattip** [WarrenWeckesser/mpsci#1]
It would be nice to have a link to https://warrenweckesser.github.io/mpsci/ somewhere in the readme and/or in the repo description

**Comment by WarrenWeckesser** [comment]
Good idea, thanks.

In https://github.com/WarrenWeckesser/mpsci/commit/15dffd29395f783f866301b2023a75af7cb2a06f, I added a link to the documentation in README.rst.
